//test data
//test data
export const rows = [
    {

        id: 1,
        date: '08/18/2014',
        location: 'San Diego',
        incidentType: 'Actual Event/Incident',
        harm: true,
        eventType: 'Operative/Invasive Procedure',
        individuals: 'Family Member, Program Value, Another Word, Word',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',
        command: 'test'
    },
    {

        id: 2,
        date: '12/25/2019',
        location: 'Los Angelos',
        incidentType: 'Actual Event/Incident',
        harm: true,
        eventType: 'Assault, Fall, one, two, three, four, five',
        individuals: 'Patient, Visitor, another, anything',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }
    , {

        id: 3,
        date: '01/25/2020',
        location: 'New York',
        incidentType: 'Near Miss/Close Call',
        harm: false,
        eventType: 'AMA/Left Without Being Seen',
        individuals: 'Volunteer',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }

    , {

        id: 4,
        date: '12/08/2020',
        location: 'Minneapolis',
        incidentType: 'Actual Event/Incident',
        harm: false,
        eventType: 'Property Lost/Stolen',
        individuals: 'Other',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }, {

        id: 5,
        date: '06/30/2021',
        location: 'Dallas',
        incidentType: 'Near Miss/Close Call',
        harm: false,
        eventType: 'Other',
        individuals: 'Staff Member',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }, {

        id: 7,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }
    , {

        id: 8,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }
    , {

        id: 9,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }
    , {

        id: 10,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }
    , {

        id: 11,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }
    , {

        id: 12,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }, {

        id: 13,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }, {

        id: 14,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }, {

        id: 15,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }, {

        id: 16,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }, {

        id: 17,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }, {

        id: 18,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }
    , {

        id: 19,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }
    , {

        id: 20,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }
    , {

        id: 21,
        date: 'test',
        location: 'test',
        incidentType: 'Other',
        harm: 'test',
        eventType: 'test',
        individuals: 'test',
        effects: 'test',
        time: 'test',
        patientSSN: 'test',
        patientPhone: 'test',
        patientAddress: 'test',
        patientName: 'test',
        witness1Name: 'test',
        witness1Phone: 'test',
        witness2Name: 'test',
        witness2Phone: 'test',
        witness3Name: 'test',
        witness3Phone: 'test',
        department: 'test',
        description: 'test',
        prevention: 'test',

        command: 'test'
    }

];